'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let statusFilter='all';
let token='', jobId='', items=[], selected=null, mode='original', busy=false, configured=false, signature='', changesSignature='', configSaving=false;
const names={pending:'待校验',processing:'校验中',done:'已校验',failed:'校验失败',stopped:'已停止',interrupted:'可继续校验',stale:'原文已更新'};
async function api(path,body){return window.parent.workbench.request('proofread',path,body);}
function error(s){$('alert').textContent=s;$('alert').hidden=!s;}
function toast(s){$('toast').textContent=s;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,2600);}
function render(){const query=$('search').value.trim();const visible=items.filter(x=>(statusFilter==='all'||x.proofread.status===statusFilter)&&x.title.includes(query));$('count').textContent=statusFilter==='all'&&!query?items.length+' 篇':`显示 ${visible.length} / ${items.length} 篇`;for(const button of $('status-filters').querySelectorAll('[data-status]')){const status=button.dataset.status,count=status==='all'?items.length:items.filter(x=>x.proofread.status===status).length;button.textContent=`${status==='all'?'全部':names[status]}（${count}）`;button.classList.toggle('selected',status===statusFilter);button.setAttribute('aria-pressed',String(status===statusFilter));}const sig=JSON.stringify([visible,busy,configured,statusFilter,query]);if(sig===signature)return;signature=sig;$('items').innerHTML=visible.map(x=>{const p=x.proofread;return `<tr><td>${esc(x.title)}${p.error?`<small>${esc(p.error)}</small>`:''}</td><td>${x.chars}</td><td>${names[p.status]||esc(p.status)}${p.status==='processing'?` ${p.completed_batches}/${p.total_batches} 组`:p.status==='done'?`<small>${p.fixed} 处修改 · ${p.review?`<button class="review-link" data-id="${x.id}" data-view="review">${p.review} 处待复核</button>`:`0 处待复核`}</small>`:''}</td><td><button data-id="${x.id}">${p.status==='done'?'查看结果':'查看 / 校验'}</button></td></tr>`;}).join('')||'<tr><td colspan="4">暂无符合条件的文案</td></tr>';}
function showDetail(){if(!selected)return;const p=selected.proofread,done=p.status==='done';$('detail-title').textContent=selected.title;$('detail-status').textContent=done?`已应用 ${p.fixed} 处修改，${p.review} 处待人工复核（未应用）。本篇已记录输入 ${p.usage.prompt_tokens} / 输出 ${p.usage.completion_tokens} tokens。`:((names[p.status]||p.status)+(p.status==='processing'?` · ${p.completed_batches}/${p.total_batches} 组`:'')+(p.error?' · '+p.error:''));$('show-corrected').disabled=!done;$('show-changes').disabled=!done;$('show-review').disabled=!done;$('show-changes').textContent=`全部对照（${(p.changes||[]).length}）`;$('show-review').textContent=`待复核（${p.review||0}）`;if(!done&&mode!=='original')mode='original';for(const m of ['original','corrected','changes','review'])$('show-'+m).classList.toggle('selected',mode===m);const comparison=mode==='changes'||mode==='review';$('detail-text').hidden=comparison;$('changes').hidden=!comparison;const text=mode==='corrected'?p.text:selected.original;if($('detail-text').textContent!==text)$('detail-text').textContent=text;const cs=JSON.stringify([selected.id,mode,p.changes]);if(cs!==changesSignature){changesSignature=cs;$('changes').innerHTML=(p.changes||[]).filter(c=>mode!=='review'||c.kind==='review').map(c=>`<div class="change ${c.kind==='review'?'needs-review':''}"><strong>第 ${c.id} 条 · ${c.kind==='fix'?'已应用':'待复核，未应用'}</strong><p><del>${esc(c.before)}</del></p><p><ins>${esc(c.after)}</ins></p><small>${esc(c.reason)}</small>${c.kind==='fix'?`<p><button data-keep="${c.id}">保留原文</button></p>`:''}</div>`).join('')||(mode==='review'?'<p>本篇没有待复核内容。</p>':'<p>未发现需要修改的内容。</p>');} $('start-one').hidden=done;$('start-one').disabled=busy||!configured;$('start-one').textContent=['failed','stopped','interrupted'].includes(p.status)?'继续校验这篇':'校验这篇文案';const base=`/api/jobs/${jobId}/items/${selected.id}`;for(const k of ['txt','srt','zip','open'])$(k).hidden=!done;$('txt').href=base+'/files/'+encodeURIComponent('校对.txt');$('srt').href=base+'/files/'+encodeURIComponent('校对.srt');$('zip').href=base+'/export';$('video').href=selected.url;$('output').textContent=done?'保存至 '+p.output_dir:'';$('copy').hidden=comparison;}
async function refresh(){try{const inf=await api('/info');error('');token=inf.token;busy=inf.queue.running;configured=inf.configured;configControls();$('connection').textContent=configured?inf.model+' · 密钥已配置':'尚未配置密钥';$('batch').disabled=busy||!configured||!items.some(x=>x.proofread.status!=='done');$('stop').hidden=!busy;const q=inf.queue;$('queue').textContent=q.total?`${q.running?'正在校验':'本次校验结束'}：完成 ${q.completed} / ${q.total} 篇，失败 ${q.failed} 篇${q.current_title?' · '+q.current_title:''}`:'可先打开一篇文案试用，再决定是否批量校验。';if(jobId){const j=await api('/jobs/'+jobId);items=j.items;render();if(selected&&$('detail').open){selected=await api(`/jobs/${jobId}/items/${selected.id}`);showDetail();}}}catch(e){error(e.message);}finally{setTimeout(refresh,2200);}}
async function start(itemId){error('');try{await api(`/jobs/${jobId}/start`,itemId?{item_id:itemId}:{});busy=true;$('batch').disabled=true;$('start-one').disabled=true;toast('校验已开始');}catch(e){error(e.message);toast(e.message);}}
$('batch').onclick=()=>start(null);$('start-one').onclick=()=>start(selected.id);$('stop').onclick=async()=>{try{await api('/stop',{});toast('将在当前 API 请求结束后停止');}catch(e){error(e.message);}};
$('changes').onclick=async e=>{const b=e.target.closest('[data-keep]');if(!b)return;b.disabled=true;try{await api(`/jobs/${jobId}/items/${selected.id}/keep-original`,{cue_ids:[Number(b.dataset.keep)]});selected=await api(`/jobs/${jobId}/items/${selected.id}`);showDetail();toast('已保留原文，TXT 与 SRT 已同步更新');}catch(e){toast(e.message);b.disabled=false;}};
$('jobs').onchange=async()=>{jobId=$('jobs').value;selected=null;const j=await api('/jobs/'+jobId);items=j.items;render();};$('search').oninput=render;
$('status-filters').onclick=e=>{const b=e.target.closest('[data-status]');if(!b)return;statusFilter=b.dataset.status;render();};
$('items').onclick=async e=>{const b=e.target.closest('[data-id]');if(!b)return;try{selected=await api(`/jobs/${jobId}/items/${b.dataset.id}`);mode=selected.proofread.status==='done'?(b.dataset.view==='review'?'review':'changes'):'original';showDetail();$('detail').showModal();$('changes').scrollTop=0;}catch(e){error(e.message);}};
for(const m of ['original','corrected','changes','review'])$('show-'+m).onclick=()=>{mode=m;showDetail();$('changes').scrollTop=0;};$('close').onclick=()=>$('detail').close();$('open').onclick=async()=>{try{await api(`/jobs/${jobId}/items/${selected.id}/open`,{});}catch(e){toast(e.message);}};$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(mode==='corrected'?selected.proofread.text:selected.original);toast('已复制');}catch{toast('请选中文字后使用 ⌘C 复制');}};
function configControls(){for(const id of ['save-config','import-config','clear-config'])$(id).disabled=busy||configSaving||!token;$('edit-config').disabled=busy;}
function renderConfig(c){configured=c.configured;$('config-status').textContent=configured?'本机已配置千问密钥，可使用文案校验。密钥不回显。':'请先配置自己的 API Key，才能使用文案校验。';$('api-base').value=c.base_url;$('api-key').value='';$('config-form').hidden=configured;$('clear-config').hidden=!configured;$('edit-config').textContent=configured?'修改配置':'配置密钥';configControls();}
$('edit-config').onclick=()=>{$('config-form').hidden=!$('config-form').hidden;if(!$('config-form').hidden)$('api-key').focus();};
async function saveConfig(body){configSaving=true;configControls();$('config-feedback').textContent='正在保存…';try{const c=await api('/config',body);renderConfig(c);$('config-feedback').textContent='配置已保存到本机。开始校验时会使用你的百炼账户。';}catch(e){$('config-feedback').textContent=e.message;}finally{$('api-key').value='';$('config-csv').value='';configSaving=false;configControls();}}
$('config-form').onsubmit=e=>{e.preventDefault();saveConfig({api_key:$('api-key').value,base_url:$('api-base').value});};
$('import-config').onclick=()=>$('config-csv').click();
$('config-csv').onchange=async()=>{const f=$('config-csv').files[0];if(!f)return;if(f.size>20000){$('config-feedback').textContent='请选择百炼导出的密钥 CSV，文件应小于 20KB。';$('config-csv').value='';return;}try{await saveConfig({csv_data:await f.text()});}catch{$('config-feedback').textContent='无法读取 CSV，请重新选择。';$('config-csv').value='';}};
$('clear-config').onclick=async()=>{configSaving=true;configControls();try{renderConfig(await api('/config/clear',{}));$('config-feedback').textContent='已清除本机密钥，重新配置后才能发起校验。';}catch(e){$('config-feedback').textContent=e.message;}finally{configSaving=false;configControls();}};
async function init(){try{const inf=await api('/info');token=inf.token;renderConfig(await api('/config'));const jobs=await api('/jobs');$('jobs').innerHTML=jobs.map(j=>`<option value="${j.id}">${esc(j.author||'提取任务')} · ${esc(j.created_at.slice(5,16).replace('T',' '))} · ${j.done} 篇已完成</option>`).join('');jobId=jobs[0]?.id||'';refresh();}catch(e){error(e.message);}}init();
